---
smdownloadurl: "https://hb.bizmrg.com/distributions/Raspberry%20Pi/X64/api.smartplayer.org/default%20(ds)/SmartPlayer_api_1.66.1.deb"
smdownloadurldest: "/tmp/package.deb"
useuser: pi
updateos: false
##### PACKAGES #####
toinstall:
  - qtav-players
  - libxslt1.1
  - libxss1
  - libwebpdemux2
  - libnss3
  - alsa-utils
  - xserver-xorg
  - x11-xserver-utils
  - x11-utils
  - vlc
  # Future function to turn off the screen?
  - cec-utils
# toremove: 
#   - noneforthemoment

templatestoapply:
  # Services
  - srctpl: "xorg.service.j2"
    desttpl: "/etc/systemd/system/xorg.service"
    modetpl: "0644"
    overwrite: "yes"

  - srctpl: "smartplayer.service.j2"
    desttpl: "/etc/systemd/system/smartplayer.service"
    modetpl: "0644"
    overwrite: "yes"

manageservices:
  - xorg.service
  - smartplayer.service