---
- name: "Manage services"
  systemd:
    name: "{{ item }}"
    state: restarted
    enabled: yes
    daemon_reload: yes
  with_items: "{{ manageservices }}"
  ignore_errors: yes

- name: "Suggest reboot"
  debug:
    msg:
    - "Reboot is needed to apply system configuration"